//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\shotpeening\application\GeometricProcessFaceClassification.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: PC
//              Version: NX 2306
//              Date: 07-10-2025  (Format: mm-dd-yyyy)
//              Time: 12:53 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "GeometricProcessFaceClassification.hpp"
#include "FaceProcessor.h"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(GeometricProcessFaceClassification::theSession) = NULL;
UI *(GeometricProcessFaceClassification::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
GeometricProcessFaceClassification::GeometricProcessFaceClassification()
{
    try
    {
        // Initialize the NX Open C++ API environment
        GeometricProcessFaceClassification::theSession = NXOpen::Session::GetSession();
        GeometricProcessFaceClassification::theUI = UI::GetUI();
        theDlxFileName = "GeometricProcessFaceClassification.dlx";
        theDialog = GeometricProcessFaceClassification::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &GeometricProcessFaceClassification::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &GeometricProcessFaceClassification::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &GeometricProcessFaceClassification::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &GeometricProcessFaceClassification::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &GeometricProcessFaceClassification::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
GeometricProcessFaceClassification::~GeometricProcessFaceClassification()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//This method launches the dialog to screen
//------------------------------------------------------------------------------
NXOpen::BlockStyler::BlockDialog::DialogResponse GeometricProcessFaceClassification::Launch()
{
    NXOpen::BlockStyler::BlockDialog::DialogResponse dialogResponse= NXOpen::BlockStyler::BlockDialog::DialogResponse::DialogResponseInvalid;
    try
    {
        dialogResponse=theDialog->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        GeometricProcessFaceClassification::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return dialogResponse;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void GeometricProcessFaceClassification::initialize_cb()
{
    try
    {
        typegroup = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("typegroup"));
        bodySelect0 = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodySelect0"));
        filletthreshhold = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("filletthreshhold"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        regroupbutton = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("regroupbutton"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        face_select0 = dynamic_cast<NXOpen::BlockStyler::FaceCollector*>(theDialog->TopBlock()->FindBlock("face_select0"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        label0 = dynamic_cast<NXOpen::BlockStyler::Label*>(theDialog->TopBlock()->FindBlock("label0"));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        GeometricProcessFaceClassification::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void GeometricProcessFaceClassification::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        GeometricProcessFaceClassification::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int GeometricProcessFaceClassification::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
        int currentType = enum0->GetProperties()->GetEnum("Value");
        FaceRegionType displayedType = static_cast<FaceRegionType>(currentType);

        std::vector<TaggedObject*> userSelectedFaces = face_select0->GetSelectedObjects();

        std::vector<TaggedObject*> originalFaces = faceprocessor0.GetOneRegionFaces(displayedType);

        faceprocessor0.HandleUserFaceEdits(displayedType, userSelectedFaces);
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        GeometricProcessFaceClassification::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int GeometricProcessFaceClassification::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == bodySelect0)
        {
        //---------Enter your code here-----------
            faceprocessor0.classifyFaces(bodySelect0->GetSelectedObjects());

            int type = enum0->GetProperties()->GetEnum("Value");
            switch (type)
            {
            case 0:
                face_select0->SetSelectedObjects(faceprocessor0.GetOneRegionFaces(FaceRegionType::HORIZONTAL));
                break;
            case 1:
                face_select0->SetSelectedObjects(faceprocessor0.GetOneRegionFaces(FaceRegionType::CONVEX));
                break;
            case 2:
                face_select0->SetSelectedObjects(faceprocessor0.GetOneRegionFaces(FaceRegionType::CONCAVE));
                break;
            case 3:
                face_select0->SetSelectedObjects(faceprocessor0.GetOneRegionFaces(FaceRegionType::SIDEWALL));
                break;
            }

            faceprocessor0.SetFacesColor();

            face_select0->Focus();
        }
        else if(block == filletthreshhold)
        {
        //---------Enter your code here-----------
            faceprocessor0.m_minRadiusThreshold = filletthreshhold->Value();
        }
        else if(block == enum0)
        {
        //---------Enter your code here-----------
           int type = enum0->GetProperties()->GetEnum("Value");
           switch (type)
           {
           case 0:
               face_select0->SetSelectedObjects(faceprocessor0.GetOneRegionFaces(FaceRegionType::HORIZONTAL));
               break;
           case 1:
               face_select0->SetSelectedObjects(faceprocessor0.GetOneRegionFaces(FaceRegionType::CONVEX));
               break;
           case 2:
               face_select0->SetSelectedObjects(faceprocessor0.GetOneRegionFaces(FaceRegionType::CONCAVE));
               break;
           case 3:
               face_select0->SetSelectedObjects(faceprocessor0.GetOneRegionFaces(FaceRegionType::SIDEWALL));
               break;
           }
        }
        else if(block == regroupbutton)
        {
        //---------Enter your code here-----------
            faceprocessor0.ClassifyAllFacesbyType(bodySelect0->GetSelectedObjects());
        }
        else if(block == face_select0)
        {
        //---------Enter your code here-----------

        }
        else if(block == button0)
        {
        //---------Enter your code here-----------
            int currentType = enum0->GetProperties()->GetEnum("Value");
            FaceRegionType displayedType = static_cast<FaceRegionType>(currentType);

            std::vector<TaggedObject*> userSelectedFaces = face_select0->GetSelectedObjects();

            std::vector<TaggedObject*> originalFaces = faceprocessor0.GetOneRegionFaces(displayedType);

            faceprocessor0.HandleUserFaceEdits(displayedType, userSelectedFaces);
           
        }
        else if(block == label0)
        {
        //---------Enter your code here-----------
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        GeometricProcessFaceClassification::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int GeometricProcessFaceClassification::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        GeometricProcessFaceClassification::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* GeometricProcessFaceClassification::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
