//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\shotpeening\application\SprayCurveBuilder.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: PC
//              Version: NX 2306
//              Date: 09-19-2025  (Format: mm-dd-yyyy)
//              Time: 20:29
//
//==============================================================================

#ifndef SPRAYCURVEBUILDER_H_INCLUDED
#define SPRAYCURVEBUILDER_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>
#include <NXOpen/BlockStyler_ListBox.hxx>
#include <NXOpen/BlockStyler_CurveCollector.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_Button.hxx>

#include "RegionBuilder.h"
#include "RegionCurveBuilder.h"
#include "regionstruct.h"


//------------------------------------------------------------------------------
//Bit Option for Property: EntityType
//------------------------------------------------------------------------------
#define                         EntityType_AllowBodies (1 << 6);
//------------------------------------------------------------------------------
//Bit Option for Property: BodyRules
//------------------------------------------------------------------------------
#define                           BodyRules_SingleBody (1 << 0);
#define                        BodyRules_FeatureBodies (1 << 1);
#define                        BodyRules_BodiesinGroup (1 << 2);
#define                                 BodyRules_相切片体 (1 << 4);
#define                                 BodyRules_相邻片体 (1 << 5);
#define                                 BodyRules_相连片体 (1 << 6);
//------------------------------------------------------------------------------
//Bit Option for Property: EntityType
//------------------------------------------------------------------------------
#define                          EntityType_AllowEdges (1 << 0);
#define                         EntityType_AllowCurves (1 << 2);
#define                          EntityType_AllowPoint (1 << 3);
//------------------------------------------------------------------------------
//Bit Option for Property: CurveRules
//------------------------------------------------------------------------------
#define                         CurveRules_SingleCurve (1 << 0);
#define                     CurveRules_ConnectedCurves (1 << 1);
#define                       CurveRules_TangentCurves (1 << 2);
#define                           CurveRules_FaceEdges (1 << 3);
#define                           CurveRules_BodyEdges (1 << 4);
#define                          CurveRules_SheetEdges (1 << 5);
#define                       CurveRules_FeatureCurves (1 << 6);
#define                         CurveRules_VertexEdges (1 << 8);
#define                  CurveRules_VertexTangentEdges (1 << 9);
#define                CurveRules_RegionBoundaryCurves (1 <<11);
#define                   CurveRules_OuterEdgesofFaces (1 <<13);
#define                     CurveRules_RibTopFaceEdges (1 <<14);
#define            CurveRules_FeatureIntersectionEdges (1 <<15);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport SprayCurveBuilder
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    SprayCurveBuilder();
    ~SprayCurveBuilder();
    NXOpen::BlockStyler::BlockDialog::DialogResponse Launch();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the SprayCurveBuilder.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
    //int AddCallback (NXOpen::BlockStyler::ListBox* list_box);
    //int DeleteCallback(NXOpen::BlockStyler::ListBox* list_box);
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::BodyCollector* bodySelect0;// Block type: Body Collector
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::ListBox* reg_box;// Block type: List Box
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::CurveCollector* highlightselection;// Block type: Curve Collector
    NXOpen::BlockStyler::ListBox* crv_box;// Block type: List Box
    NXOpen::BlockStyler::Group* group3;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* d_sprayDiameter;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* d_overlapRatio;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* d_smallEdgeThreshold;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* d_tinyEdgeThreshold;// Block type: Double
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    NXOpen::BlockStyler::Button* button01;// Block type: Button

    RegionBuilder m_regionbuilder;
    
    void set_regbox_item(RegionBuilder& regionbuilder);
    void regbox_select_update();
    void crvbox_select_update();
    RegionCurveBuilder m_curveBuilder;  // 添加成员变量
    void GenerateSprayPath();           // 生成喷砂路径的函数


};
#endif //SPRAYCURVEBUILDER_H_INCLUDED
