//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Siemens\CustomFunction\application\SpraySequencerandCSVOutputDialog.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: 10609
//              Version: NX 2412
//              Date: 11-14-2025  (Format: mm-dd-yyyy)
//              Time: 10:12
//
//==============================================================================

#ifndef SPRAYSEQUENCERANDCSVOUTPUTDIALOG_H_INCLUDED
#define SPRAYSEQUENCERANDCSVOUTPUTDIALOG_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_CurveCollector.hxx>
#include <NXOpen/BlockStyler_SpecifyPoint.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_ListBox.hxx>
#include <NXOpen/BlockStyler_SelectObject.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>

//------------------------------------------------------------------------------
// 自定义包含
//------------------------------------------------------------------------------
#include "SprayPathConnector.h"
//#include "SprayPathSequencer.h"
#include "CSVExporter.h"
#include <sstream>
#include <iomanip>

//------------------------------------------------------------------------------
//Bit Option for Property: EntityType
//------------------------------------------------------------------------------
#define                          EntityType_AllowEdges (1 << 0);
#define                         EntityType_AllowCurves (1 << 2);
#define                          EntityType_AllowPoint (1 << 3);
#define                         EntityType_AllowBodies (1 << 6);
//------------------------------------------------------------------------------
//Bit Option for Property: CurveRules
//------------------------------------------------------------------------------
#define                         CurveRules_SingleCurve (1 << 0);
#define                     CurveRules_ConnectedCurves (1 << 1);
#define                       CurveRules_TangentCurves (1 << 2);
#define                           CurveRules_FaceEdges (1 << 3);
#define                           CurveRules_BodyEdges (1 << 4);
#define                          CurveRules_SheetEdges (1 << 5);
#define                       CurveRules_FeatureCurves (1 << 6);
#define                         CurveRules_VertexEdges (1 << 8);
#define                  CurveRules_VertexTangentEdges (1 << 9);
#define                CurveRules_RegionBoundaryCurves (1 <<11);
#define                   CurveRules_OuterEdgesofFaces (1 <<13);
#define                     CurveRules_RibTopFaceEdges (1 <<14);
#define            CurveRules_FeatureIntersectionEdges (1 <<15);
#define                              CurveRules_组合面边界边 (1 <<16);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesEnabled
//------------------------------------------------------------------------------
#define              SnapPointTypesEnabled_UserDefined (1 << 0);
#define                 SnapPointTypesEnabled_Inferred (1 << 1);
#define           SnapPointTypesEnabled_ScreenPosition (1 << 2);
#define                 SnapPointTypesEnabled_EndPoint (1 << 3);
#define                 SnapPointTypesEnabled_MidPoint (1 << 4);
#define             SnapPointTypesEnabled_ControlPoint (1 << 5);
#define             SnapPointTypesEnabled_Intersection (1 << 6);
#define                SnapPointTypesEnabled_ArcCenter (1 << 7);
#define            SnapPointTypesEnabled_QuadrantPoint (1 << 8);
#define            SnapPointTypesEnabled_ExistingPoint (1 << 9);
#define             SnapPointTypesEnabled_PointonCurve (1 <<10);
#define           SnapPointTypesEnabled_PointonSurface (1 <<11);
#define         SnapPointTypesEnabled_PointConstructor (1 <<12);
#define     SnapPointTypesEnabled_TwocurveIntersection (1 <<13);
#define             SnapPointTypesEnabled_TangentPoint (1 <<14);
#define                    SnapPointTypesEnabled_Poles (1 <<15);
#define         SnapPointTypesEnabled_BoundedGridPoint (1 <<16);
#define         SnapPointTypesEnabled_FacetVertexPoint (1 <<17);
#define            SnapPointTypesEnabled_DefiningPoint (1 <<18);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesOnByDefault
//------------------------------------------------------------------------------
#define          SnapPointTypesOnByDefault_UserDefined (1 << 0);
#define             SnapPointTypesOnByDefault_Inferred (1 << 1);
#define       SnapPointTypesOnByDefault_ScreenPosition (1 << 2);
#define             SnapPointTypesOnByDefault_EndPoint (1 << 3);
#define             SnapPointTypesOnByDefault_MidPoint (1 << 4);
#define         SnapPointTypesOnByDefault_ControlPoint (1 << 5);
#define         SnapPointTypesOnByDefault_Intersection (1 << 6);
#define            SnapPointTypesOnByDefault_ArcCenter (1 << 7);
#define        SnapPointTypesOnByDefault_QuadrantPoint (1 << 8);
#define        SnapPointTypesOnByDefault_ExistingPoint (1 << 9);
#define         SnapPointTypesOnByDefault_PointonCurve (1 <<10);
#define       SnapPointTypesOnByDefault_PointonSurface (1 <<11);
#define     SnapPointTypesOnByDefault_PointConstructor (1 <<12);
#define SnapPointTypesOnByDefault_TwocurveIntersection (1 <<13);
#define         SnapPointTypesOnByDefault_TangentPoint (1 <<14);
#define                SnapPointTypesOnByDefault_Poles (1 <<15);
#define     SnapPointTypesOnByDefault_BoundedGridPoint (1 <<16);
#define     SnapPointTypesOnByDefault_FacetVertexPoint (1 <<17);
#define        SnapPointTypesOnByDefault_DefiningPoint (1 <<18);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport SpraySequencerandCSVOutputDialog
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    SpraySequencerandCSVOutputDialog();
    ~SpraySequencerandCSVOutputDialog();
    NXOpen::BlockStyler::BlockDialog::DialogResponse Launch();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the SpraySequencerandCSVOutputDialog.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    int filter_cb(NXOpen::BlockStyler::UIBlock*  block, NXOpen::TaggedObject* selectObject);
    PropertyList* GetBlockProperties(const char *blockID);
    
    //int AddCallback (NXOpen::BlockStyler::ListBox* list_box);
    //int DeleteCallback(NXOpen::BlockStyler::ListBox* list_box);
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::CurveCollector* all_curves_sel;// Block type: Curve Collector
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::CurveCollector* start_curve_sel;// Block type: Curve Collector
    NXOpen::BlockStyler::SpecifyPoint* startpoint_sel;// Block type: Specify Point
    NXOpen::BlockStyler::Button* optlink_but;// Block type: Button
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::ListBox* curve_sequence_list;// Block type: List Box
    NXOpen::BlockStyler::SelectObject* highlight_select;// Block type: Selection
    NXOpen::BlockStyler::Group* group3;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* sprayangle_double;// Block type: Double
    NXOpen::BlockStyler::SelectObject* csv_curve_select;// Block type: Selection
    NXOpen::BlockStyler::Button* csv_output_button;// Block type: Button

    //==========================================================================
    // 自定义成员变量和方法
    //==========================================================================
    SprayPathConnector m_pathSequencer;  // 路径优化器实例

    // 主要功能方法
    void OptimizeAndDisplayPaths();      // 执行优化并显示结果
    void SetStartConstraints();          // 设置起点约束
    void PopulateCurveSequenceList();    // 填充结果列表


    // 消息弹窗辅助函数
    void ShowErrorMessage(const char* message);
    void ShowInfoMessage(const char* message);
    void ShowWarningMessage(const char* message);

    // CSV导出相关（委托给 CSVExporter 工具类）
    void ExportCSVFiles();  // UI 回调函数，调用 CSVExporter::ExportCSVFiles
    
};
#endif //SPRAYSEQUENCERANDCSVOUTPUTDIALOG_H_INCLUDED
