//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Siemens\CustomFunction\application\SpraySequencerandCSVOutputDialog.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: 10609
//              Version: NX 2412
//              Date: 11-14-2025  (Format: mm-dd-yyyy)
//              Time: 10:12 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "SpraySequencerandCSVOutputDialog.hpp"
#include "HelpFunction.h"
#include <uf_vec.h>
#include <fstream>
#include <chrono>
#include <ctime>
#include <direct.h>  // For _mkdir on Windows
#include <sys/stat.h>
#include <unordered_map>
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(SpraySequencerandCSVOutputDialog::theSession) = NULL;
UI *(SpraySequencerandCSVOutputDialog::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
SpraySequencerandCSVOutputDialog::SpraySequencerandCSVOutputDialog()
{
    try
    {
        // Initialize the NX Open C++ API environment
        SpraySequencerandCSVOutputDialog::theSession = NXOpen::Session::GetSession();
        SpraySequencerandCSVOutputDialog::theUI = UI::GetUI();
        theDlxFileName = "SpraySequencerandCSVOutputDialog.dlx";
        theDialog = SpraySequencerandCSVOutputDialog::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &SpraySequencerandCSVOutputDialog::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &SpraySequencerandCSVOutputDialog::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &SpraySequencerandCSVOutputDialog::update_cb));
        theDialog->AddFilterHandler(make_callback(this, &SpraySequencerandCSVOutputDialog::filter_cb));
        theDialog->AddInitializeHandler(make_callback(this, &SpraySequencerandCSVOutputDialog::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &SpraySequencerandCSVOutputDialog::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
SpraySequencerandCSVOutputDialog::~SpraySequencerandCSVOutputDialog()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//This method launches the dialog to screen
//------------------------------------------------------------------------------
NXOpen::BlockStyler::BlockDialog::DialogResponse SpraySequencerandCSVOutputDialog::Launch()
{
    NXOpen::BlockStyler::BlockDialog::DialogResponse dialogResponse= NXOpen::BlockStyler::BlockDialog::DialogResponse::DialogResponseInvalid;
    try
    {
        dialogResponse=theDialog->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SpraySequencerandCSVOutputDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return dialogResponse;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void SpraySequencerandCSVOutputDialog::initialize_cb()
{
    try
    {
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        all_curves_sel = dynamic_cast<NXOpen::BlockStyler::CurveCollector*>(theDialog->TopBlock()->FindBlock("all_curves_sel"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        start_curve_sel = dynamic_cast<NXOpen::BlockStyler::CurveCollector*>(theDialog->TopBlock()->FindBlock("start_curve_sel"));
        startpoint_sel = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("startpoint_sel"));
        optlink_but = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("optlink_but"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        curve_sequence_list = dynamic_cast<NXOpen::BlockStyler::ListBox*>(theDialog->TopBlock()->FindBlock("curve_sequence_list"));
        highlight_select = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("highlight_select"));
        group3 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));
        sprayangle_double = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("sprayangle_double"));
        csv_curve_select = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("csv_curve_select"));
        csv_output_button = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("csv_output_button"));
        //------------------------------------------------------------------------------
        //Registration of ListBox specific callbacks
        //------------------------------------------------------------------------------
        //curve_sequence_list->SetAddHandler(make_callback(this, &SpraySequencerandCSVOutputDialog::AddCallback));
        
        //curve_sequence_list->SetDeleteHandler(make_callback(this, &SpraySequencerandCSVOutputDialog::DeleteCallback));
        
        //------------------------------------------------------------------------------
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SpraySequencerandCSVOutputDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void SpraySequencerandCSVOutputDialog::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
		csv_curve_select->SetSelectModeAsString("Multiple");
		highlight_select->SetShow(true);
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        SpraySequencerandCSVOutputDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int SpraySequencerandCSVOutputDialog::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----

    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        SpraySequencerandCSVOutputDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int SpraySequencerandCSVOutputDialog::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if (block == all_curves_sel)
        {
            //---------Enter your code here-----------
        }
        else if (block == start_curve_sel)
        {
            //---------Enter your code here-----------
        }
        else if (block == startpoint_sel)
        {
            //---------Enter your code here-----------
        }
        else if (block == optlink_but)
        {
            OptimizeAndDisplayPaths();
        }
        else if (block == curve_sequence_list)
        {
            // 获取列表中选择的项索引
            PropertyList* listProps = curve_sequence_list->GetProperties();
            std::vector<int> selectedIndices = listProps->GetIntegerVector("SelectedItems");
            delete listProps;

            // 如果有选中项，高亮显示对应曲线
            if (!selectedIndices.empty()) {
                int selectedIdx = selectedIndices[0];  // 获取第一个选中项

                // 获取优化后的曲线列表
                std::vector<NXOpen::TaggedObject*> optimizedCurves = m_pathSequencer.getOptimizedCurves();

                // 检查索引有效性
                if (selectedIdx >= 0 && selectedIdx < (int)optimizedCurves.size()) {
                    // 将对应曲线设置到 highlight_select
                    NXOpen::TaggedObject* selectedCurve = optimizedCurves[selectedIdx];
                    std::vector<NXOpen::TaggedObject*> highlightList;
                    highlightList.push_back(selectedCurve);

					highlight_select->SetSelectedObjects(highlightList);

                    // 设置焦点到 highlight_select
                    highlight_select->Focus();
                }
            }
        }
        else if (block == highlight_select)
        {
            //---------Enter your code here-----------
        }
        else if (block == sprayangle_double)
        {
            //---------Enter your code here-----------
        }
        else if (block == csv_curve_select)
        {
            //---------Enter your code here-----------
        }
        else if (block == csv_output_button)
        {
            ExportCSVFiles();
        }
    }
    catch (exception& ex)
    {
        //---- Enter your exception handling code here -----
        SpraySequencerandCSVOutputDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int SpraySequencerandCSVOutputDialog::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        SpraySequencerandCSVOutputDialog::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: filter_cb
//------------------------------------------------------------------------------
int SpraySequencerandCSVOutputDialog::filter_cb(NXOpen::BlockStyler::UIBlock* block, NXOpen::TaggedObject* selectObject)
{
    // 对曲线选择器应用 IsSprayPath 属性过滤
    if (block == all_curves_sel || block == start_curve_sel || block == csv_curve_select) {
        try {
            NXOpen::NXObject* nxObj = dynamic_cast<NXOpen::NXObject*>(selectObject);
            if (nxObj != nullptr) {
                // 检查曲线是否有 IsSprayPath 属性且值为 1
                int isSprayPath = nxObj->GetIntegerAttribute("IsSprayPath");
                if (isSprayPath == 1) {
                    return UF_UI_SEL_ACCEPT;
                }
            }
        }
        catch (...) {
            // 属性不存在或读取失败，拒绝选择
        }
        return UF_UI_SEL_REJECT;
    }

    return(UF_UI_SEL_ACCEPT);
}
//------------------------------------------------------------------------------
//ListBox specific callbacks
//------------------------------------------------------------------------------
//int SpraySequencerandCSVOutputDialog::AddCallback (NXOpen::BlockStyler::ListBox* list_box)
//{
//}

//int SpraySequencerandCSVOutputDialog::DeleteCallback(NXOpen::BlockStyler::ListBox* list_box)
//{
//}

//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* SpraySequencerandCSVOutputDialog::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}



//------------------------------------------------------------------------------
// 消息弹窗辅助函数
//------------------------------------------------------------------------------
void SpraySequencerandCSVOutputDialog::ShowErrorMessage(const char* message)
{
    theUI->NXMessageBox()->Show("错误",
        NXOpen::NXMessageBox::DialogTypeError,
        message);
}

void SpraySequencerandCSVOutputDialog::ShowInfoMessage(const char* message)
{
    theUI->NXMessageBox()->Show("提示",
        NXOpen::NXMessageBox::DialogTypeInformation,
        message);
}

void SpraySequencerandCSVOutputDialog::ShowWarningMessage(const char* message)
{
    theUI->NXMessageBox()->Show("警告",
        NXOpen::NXMessageBox::DialogTypeWarning,
        message);
}

//------------------------------------------------------------------------------
// 设置起点约束
//------------------------------------------------------------------------------
void SpraySequencerandCSVOutputDialog::SetStartConstraints()
{
    // 获取起点位置
    Point3d startPoint = startpoint_sel->Point();

    // 获取起点曲线
    PropertyList* curveProps = start_curve_sel->GetProperties();
    std::vector<TaggedObject*> startCurves =
        curveProps->GetTaggedObjectVector("SelectedObjects");
    delete curveProps;

    // 设置约束
    if (!startCurves.empty()) {
        // 通过点找最近端点（自动匹配曲线）
        m_pathSequencer.setStartByPickedPoint(startPoint);
    }
    else {
        // 如果未选择起点曲线，清除约束
        m_pathSequencer.clearStartConstraint();
    }
}

//------------------------------------------------------------------------------
// 填充优化序列到列表
//------------------------------------------------------------------------------
void SpraySequencerandCSVOutputDialog::PopulateCurveSequenceList()
{
    // 获取优化后的序列
    std::vector<std::pair<int, bool>> sequence =
        m_pathSequencer.getFinalSequence();

    // 构建列表项字符串
    std::vector<NXString> itemStrings;
    for (size_t i = 0; i < sequence.size(); i++) {
        int pathIdx = sequence[i].first;

        //  bool 含义是 entryIsStart (true=正向, false=反向)
        bool entryIsStart = sequence[i].second;

        // 格式: "序号  1: 路径  5 [正向]"
        std::stringstream ss;
        ss << "序号 " << std::setw(3) << (i + 1)
            << ": 路径 " << std::setw(3) << pathIdx
            << (entryIsStart ? " [正向]" : " [反向]"); // <--- 修改这里：判断逻辑反转
        // --- 修改结束 ---

        itemStrings.push_back(ss.str());
    }

    // 设置列表项
    PropertyList* listProps = curve_sequence_list->GetProperties();
    listProps->SetStrings("ListItems", itemStrings);
    delete listProps;
}

//------------------------------------------------------------------------------
// 执行优化并显示结果
//------------------------------------------------------------------------------
void SpraySequencerandCSVOutputDialog::OptimizeAndDisplayPaths()
{
    // Step 1: 清空之前的数据
    m_pathSequencer.clearPaths();

    // Step 2: 获取选中的喷涂曲线
    PropertyList* allCurvesProps = all_curves_sel->GetProperties();
    std::vector<TaggedObject*> selectedCurves =
        allCurvesProps->GetTaggedObjectVector("SelectedObjects");
    delete allCurvesProps;

    // Step 3: 验证曲线数量
    if (selectedCurves.empty()) {
        ShowErrorMessage("请选择喷涂路径曲线！");
        return;
    }

    if (selectedCurves.size() < 3) {
        ShowErrorMessage("请至少选择3条曲线才能启动遗传算法优化！");
        return;
    }

    // Step 4: 添加路径到优化器
    m_pathSequencer.addPathsFromUI(selectedCurves);

    // Step 5: 设置起点约束
    SetStartConstraints();

    // Step 6: 执行遗传算法优化
    m_pathSequencer.solve();

    // Step 7: 填充结果到列表
    PopulateCurveSequenceList();

    // Step 8: 自动填充优化后的曲线到 CSV 选择器
    std::vector<NXOpen::TaggedObject*> optimizedCurves = m_pathSequencer.getOptimizedCurves();
    if (!optimizedCurves.empty()) {
        PropertyList* csvSelectProps = csv_curve_select->GetProperties();
        csvSelectProps->SetTaggedObjectVector("SelectedObjects", optimizedCurves);
        delete csvSelectProps;
    }

    // Step 9: 创建可视化连接线（Layer 89）
   m_pathSequencer.createConnectionLines();

    // Step 10: 生成详细日志文件
    m_pathSequencer.printResult();

    // Step 11: 弹窗提示优化完成
    double distance = m_pathSequencer.getBestDistance();
    std::stringstream msg;
    msg << "遗传算法优化完成！\n\n"
        << "曲线数量: " << selectedCurves.size() << "\n"
        << "总空移距离: " << std::fixed << std::setprecision(2)
        << distance << " mm\n\n"
        << "优化序列已显示在列表中\n";

    ShowInfoMessage(msg.str().c_str());
}



//------------------------------------------------------------------------------
// 主CSV导出函数 - UI回调
//------------------------------------------------------------------------------
void SpraySequencerandCSVOutputDialog::ExportCSVFiles()
{
    try {
        // 从 UI 获取选中曲线
        std::vector<TaggedObject*> selectedCurves = csv_curve_select->GetSelectedObjects();

        // 验证曲线数量
        if (selectedCurves.empty()) {
            ShowErrorMessage("请先选择要导出的喷涂曲线！");
            return;
        }

        // 从 UI 获取喷涂角度
        PropertyList* angleProps = sprayangle_double->GetProperties();
        double sprayAngle = angleProps->GetDouble("Value");
        delete angleProps;

        // 调用 CSVExporter 静态工具类执行导出
        CSVExporter::ExportCSVFiles(
            selectedCurves,      // 选中的曲线列表
            sprayAngle,          // 喷涂角度
            m_pathSequencer,     // 路径排序器（获取方向信息）
            "C:\\txtfile"  // 输出目录
        );

        // 显示成功消息
        ShowInfoMessage("CSV导出成功！\n\n请查看输出目录：\nC:\\txtfile");
    }
    catch (std::exception& ex) {
        std::string errorMsg = "CSV导出过程中发生错误：\n";
        errorMsg += ex.what();
        ShowErrorMessage(errorMsg.c_str());
    }
}
