//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Siemens\CustomFunction\application\SprayEffectEvalutatorDialog.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: 10609
//              Version: NX 2412
//              Date: 11-06-2025  (Format: mm-dd-yyyy)
//              Time: 21:08
//
//==============================================================================

#ifndef SPRAYEFFECTEVALUTATORDIALOG_H_INCLUDED
#define SPRAYEFFECTEVALUTATORDIALOG_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>
#include <NXOpen/BlockStyler_CurveCollector.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_ListBox.hxx>
#include <NXOpen/BlockStyler_SelectObject.hxx>

//------------------------------------------------------------------------------
// === 新增：自定义头文件 ===
#include "SprayEffectEvaluator.h"
#include "HelpFunction.h"
#include <vector>
#include <sstream>
//------------------------------------------------------------------------------
//Bit Option for Property: EntityType
//------------------------------------------------------------------------------
#define                         EntityType_AllowBodies (1 << 6);
//------------------------------------------------------------------------------
//Bit Option for Property: BodyRules
//------------------------------------------------------------------------------
#define                           BodyRules_SingleBody (1 << 0);
#define                        BodyRules_FeatureBodies (1 << 1);
#define                        BodyRules_BodiesinGroup (1 << 2);
#define                                 BodyRules_相切片体 (1 << 4);
#define                                 BodyRules_相邻片体 (1 << 5);
#define                                 BodyRules_相连片体 (1 << 6);
#define                              BodyRules_片体和相邻片体 (1 << 7);
//------------------------------------------------------------------------------
//Bit Option for Property: EntityType
//------------------------------------------------------------------------------
#define                          EntityType_AllowEdges (1 << 0);
#define                         EntityType_AllowCurves (1 << 2);
#define                          EntityType_AllowPoint (1 << 3);
//------------------------------------------------------------------------------
//Bit Option for Property: CurveRules
//------------------------------------------------------------------------------
#define                         CurveRules_SingleCurve (1 << 0);
#define                     CurveRules_ConnectedCurves (1 << 1);
#define                       CurveRules_TangentCurves (1 << 2);
#define                           CurveRules_FaceEdges (1 << 3);
#define                           CurveRules_BodyEdges (1 << 4);
#define                          CurveRules_SheetEdges (1 << 5);
#define                       CurveRules_FeatureCurves (1 << 6);
#define                         CurveRules_VertexEdges (1 << 8);
#define                  CurveRules_VertexTangentEdges (1 << 9);
#define                CurveRules_RegionBoundaryCurves (1 <<11);
#define                   CurveRules_OuterEdgesofFaces (1 <<13);
#define                     CurveRules_RibTopFaceEdges (1 <<14);
#define            CurveRules_FeatureIntersectionEdges (1 <<15);
#define                              CurveRules_组合面边界边 (1 <<16);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesEnabled
//------------------------------------------------------------------------------
#define              SnapPointTypesEnabled_UserDefined (1 << 0);
#define                 SnapPointTypesEnabled_Inferred (1 << 1);
#define           SnapPointTypesEnabled_ScreenPosition (1 << 2);
#define                 SnapPointTypesEnabled_EndPoint (1 << 3);
#define                 SnapPointTypesEnabled_MidPoint (1 << 4);
#define             SnapPointTypesEnabled_ControlPoint (1 << 5);
#define             SnapPointTypesEnabled_Intersection (1 << 6);
#define                SnapPointTypesEnabled_ArcCenter (1 << 7);
#define            SnapPointTypesEnabled_QuadrantPoint (1 << 8);
#define            SnapPointTypesEnabled_ExistingPoint (1 << 9);
#define             SnapPointTypesEnabled_PointonCurve (1 <<10);
#define           SnapPointTypesEnabled_PointonSurface (1 <<11);
#define         SnapPointTypesEnabled_PointConstructor (1 <<12);
#define     SnapPointTypesEnabled_TwocurveIntersection (1 <<13);
#define             SnapPointTypesEnabled_TangentPoint (1 <<14);
#define                    SnapPointTypesEnabled_Poles (1 <<15);
#define         SnapPointTypesEnabled_BoundedGridPoint (1 <<16);
#define         SnapPointTypesEnabled_FacetVertexPoint (1 <<17);
#define            SnapPointTypesEnabled_DefiningPoint (1 <<18);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesOnByDefault
//------------------------------------------------------------------------------
#define             SnapPointTypesOnByDefault_EndPoint (1 << 3);
#define             SnapPointTypesOnByDefault_MidPoint (1 << 4);
#define         SnapPointTypesOnByDefault_ControlPoint (1 << 5);
#define         SnapPointTypesOnByDefault_Intersection (1 << 6);
#define            SnapPointTypesOnByDefault_ArcCenter (1 << 7);
#define        SnapPointTypesOnByDefault_QuadrantPoint (1 << 8);
#define        SnapPointTypesOnByDefault_ExistingPoint (1 << 9);
#define         SnapPointTypesOnByDefault_PointonCurve (1 <<10);
#define       SnapPointTypesOnByDefault_PointonSurface (1 <<11);
#define     SnapPointTypesOnByDefault_PointConstructor (1 <<12);
#define     SnapPointTypesOnByDefault_BoundedGridPoint (1 <<16);
#define     SnapPointTypesOnByDefault_FacetVertexPoint (1 <<17);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport SprayEffectEvalutatorDialog
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    SprayEffectEvalutatorDialog();
    ~SprayEffectEvalutatorDialog();
    NXOpen::BlockStyler::BlockDialog::DialogResponse Launch();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the SprayEffectEvalutatorDialog.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    int filter_cb(NXOpen::BlockStyler::UIBlock*  block, NXOpen::TaggedObject* selectObject);
    PropertyList* GetBlockProperties(const char *blockID);
    
    //int AddCallback (NXOpen::BlockStyler::ListBox* list_box);
    //int DeleteCallback(NXOpen::BlockStyler::ListBox* list_box);
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::BodyCollector* sheetregion_select;// Block type: Body Collector
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::CurveCollector* splinecurve_select;// Block type: Curve Collector
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::Button* evalutor_button;// Block type: Button
    NXOpen::BlockStyler::Group* group3;// Block type: Group
    NXOpen::BlockStyler::ListBox* poorarea_list;// Block type: List Box
    NXOpen::BlockStyler::SelectObject* curvepoint_sel;// Block type: Selection
    NXOpen::BlockStyler::Button* createcurve_button;// Block type: Button
    
    // === 新增：自定义成员变量 ===
    SprayEffectEvaluator* m_evaluator;                     // 评估器实例
    std::vector<BadAreaCluster> m_currentBadAreas;         // 当前badArea列表
};
#endif //SPRAYEFFECTEVALUTATORDIALOG_H_INCLUDED
